// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbCiudades
    {
        public tbCiudades()
        {
            tbClientes = new HashSet<tbClientes>();
            tbSedes = new HashSet<tbSedes>();
        }

        public string Ciu_Id { get; set; }
        public string Dep_Id { get; set; }
        public string Ciu_Descripcion { get; set; }
        public int? Ciu_Creacion { get; set; }
        public int? Ciu_Modifica { get; set; }
        public DateTime Ciu_Fecha_Creacion { get; set; }
        public DateTime? Ciu_Fecha_Modifica { get; set; }
        public bool? Ciu_Estado { get; set; }

        public virtual tbUsuarios Ciu_CreacionNavigation { get; set; }
        public virtual tbUsuarios Ciu_ModificaNavigation { get; set; }
        public virtual tbDepartamento Dep { get; set; }
        public virtual ICollection<tbClientes> tbClientes { get; set; }
        public virtual ICollection<tbSedes> tbSedes { get; set; }
    }
}