// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbCompras = new HashSet<tbCompras>();
            tbVentasEnc = new HashSet<tbVentasEnc>();
        }

        public int Cli_Id { get; set; }
        public string Cli_Nombre { get; set; }
        public string Cli_DNI { get; set; }
        public int? Ciu_Id { get; set; }
        public string Cli_Direccion { get; set; }
        public int? Cli_Creacion { get; set; }
        public int? Cli_Modifica { get; set; }
        public DateTime? Cli_Fecha_Creacion { get; set; }
        public DateTime? Cli_Fecha_Modifica { get; set; }
        public bool? Cli_Estado { get; set; }

        public virtual tbCiudades Ciu { get; set; }
        public virtual tbUsuarios Cli_CreacionNavigation { get; set; }
        public virtual tbUsuarios Cli_ModificaNavigation { get; set; }
        public virtual ICollection<tbCompras> tbCompras { get; set; }
        public virtual ICollection<tbVentasEnc> tbVentasEnc { get; set; }
    }
}