// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbCompras
    {
        public tbCompras()
        {
            tbVehiculos = new HashSet<tbVehiculos>();
        }

        public int Com_Id { get; set; }
        public int Cli_Id { get; set; }
        public int? Com_Cant { get; set; }
        public decimal? Com_Precio { get; set; }
        public DateTime? Com_Fecha { get; set; }
        public int? Com_Creacion { get; set; }
        public int? Com_Modifica { get; set; }
        public DateTime? Com_Fecha_Creacion { get; set; }
        public DateTime? Com_Fecha_Modifica { get; set; }
        public bool? Com_Estado { get; set; }

        public virtual tbClientes Cli { get; set; }
        public virtual tbUsuarios Com_CreacionNavigation { get; set; }
        public virtual tbUsuarios Com_ModificaNavigation { get; set; }
        public virtual ICollection<tbVehiculos> tbVehiculos { get; set; }
    }
}