// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbDepartamento
    {
        public tbDepartamento()
        {
            tbCiudades = new HashSet<tbCiudades>();
        }

        public string Dep_Id { get; set; }
        public string Dep_Descripcion { get; set; }
        [NotMapped]
        public string TotalEmpleados { get; set; }
        public int? Dep_Creacion { get; set; }
        public int? Dep_Modifica { get; set; }
        public DateTime? Dep_Fecha_Creacion { get; set; }
        public DateTime? Dep_Fecha_Modifica { get; set; }
        public bool? Dep_Estado { get; set; }

        public virtual tbUsuarios Dep_CreacionNavigation { get; set; }
        public virtual tbUsuarios Dep_ModificaNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudades { get; set; }
    }
}