// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbModelos
    {
        public tbModelos()
        {
            tbVehiculos = new HashSet<tbVehiculos>();
        }

        public int Mod_Id { get; set; }
        public string Mod_Descripcion { get; set; }
        public DateTime? Mod_Año { get; set; }
        public int? Mar_Id { get; set; }
        public int? Mod_Creacion { get; set; }
        public int? Mod_Modifica { get; set; }
        public DateTime? Mod_Fecha_Creacion { get; set; }
        public DateTime? Mod_Fecha_Modifica { get; set; }
        public bool? Mod_Estado { get; set; }

        public virtual tbMarcas Mar { get; set; }
        public virtual tbUsuarios Mod_CreacionNavigation { get; set; }
        public virtual tbUsuarios Mod_ModificaNavigation { get; set; }
        public virtual ICollection<tbVehiculos> tbVehiculos { get; set; }
    }
}