// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbPantallas_PorRoles = new HashSet<tbPantallas_PorRoles>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Rol_Id { get; set; }
        public string Rol_Descripcion { get; set; }
        public int? Rol_Creacion { get; set; }
        public DateTime? Rol_FechaCreacion { get; set; }
        public int? Rol_Modifica { get; set; }
        public DateTime? Rol_FechaModificacion { get; set; }
        public bool? Rol_Estado { get; set; }
        [NotMapped]
        public string FechaModificacion { get; set; }
        [NotMapped]
        public string FechaCreacion { get; set; }
        public virtual tbUsuarios Rol_CreacionNavigation { get; set; }
        public virtual tbUsuarios Rol_ModificaNavigation { get; set; }
        public virtual ICollection<tbPantallas_PorRoles> tbPantallas_PorRoles { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModificacion { get; set; }

        [NotMapped]
        public List<tbPantallas> pantallas { get; set; }

        [NotMapped]
        public List<int> PantallasID { get; set; }

    }
}