// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbSedes
    {
        public tbSedes()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
            tbVehiculos = new HashSet<tbVehiculos>();
            tbVentasEnc = new HashSet<tbVentasEnc>();
        }

        public int Sed_Id { get; set; }
        public string Sed_Descripcion { get; set; }
        public string Ciu_Id { get; set; }
        public int? Sed_Creacion { get; set; }
        public int? Sed_Modifica { get; set; }
        public DateTime Sed_Fecha_Creacion { get; set; }
        public DateTime? Sed_Fecha_Modifica { get; set; }
        public bool? Sed_Estado { get; set; }
        [NotMapped]
        public string FechaModificacion { get; set; }
        [NotMapped]
        public string FechaCreacion { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModificacion { get; set; }

        public virtual tbCiudades Ciu { get; set; }
        public virtual tbUsuarios Sed_CreacionNavigation { get; set; }
        public virtual tbUsuarios Sed_ModificaNavigation { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
        public virtual ICollection<tbVehiculos> tbVehiculos { get; set; }
        public virtual ICollection<tbVentasEnc> tbVentasEnc { get; set; }
    }
}