// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbVentasEnc
    {
        public tbVentasEnc()
        {
            tbVentasDetalle = new HashSet<tbVentasDetalle>();
        }

        public int VeE_Id { get; set; }
        public DateTime? VeE_Fecha { get; set; }
        public int? Cli_Id { get; set; }
        [NotMapped]
        public string? Cli_NombreCompleto { get; set; }
        public int? Sed_Id { get; set; }
        public int? VeE_Creacion { get; set; }
        public int? VeE_Modifica { get; set; }
        public DateTime? VeE_Fecha_Creacion { get; set; }
        public DateTime? VeE_Fecha_Modifica { get; set; }
        public bool? VeE_Estado { get; set; }

        public virtual tbClientes Cli { get; set; }
        public virtual tbSedes Sed { get; set; }
        public virtual tbUsuarios VeE_CreacionNavigation { get; set; }
        public virtual tbUsuarios VeE_ModificaNavigation { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalle { get; set; }
    }
}