// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbVehiculos
    {
        public tbVehiculos()
        {
            tbVentasDetalle = new HashSet<tbVentasDetalle>();
        }

        public string Veh_Placa { get; set; }
        public int? Mod_Id { get; set; }
        [NotMapped]
        public string Mod_Descripcion { get; set; }
        [NotMapped]
        public string Mar_Descripcion { get; set; }
        public int? Sed_Id { get; set; }
        [NotMapped]
        public string Sed_Descripcion { get; set; }
        public int? Com_Id { get; set; }
        public decimal? Com_Precio { get; set; }
        public int? Veh_Creacion { get; set; }
        public int? Veh_Modifica { get; set; }
        public DateTime? Veh_Fecha_Creacion { get; set; }
        public DateTime? Veh_Fecha_Modifica { get; set; }
        public bool? Veh_Estado { get; set; }

        public virtual tbCompras Com { get; set; }
        public virtual tbModelos Mod { get; set; }
        public virtual tbSedes Sed { get; set; }
        public virtual tbUsuarios Veh_CreacionNavigation { get; set; }
        public virtual tbUsuarios Veh_ModificaNavigation { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalle { get; set; }
    }
}