// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Grupo_Rac.Entities.Entity
{
    public partial class tbVentasDetalle
    {
        public int VeD_Id { get; set; }
        public string Veh_Placa { get; set; }
        public decimal? VeD_Precio { get; set; }
        public int? VeE_Id { get; set; }
        public int? VeD_Creacion { get; set; }
        public int? VeD_Modifica { get; set; }
        public DateTime? VeD_Fecha_Creacion { get; set; }
        public DateTime? VeD_Fecha_Modifica { get; set; }
        public bool? VeD_Estado { get; set; }

        public virtual tbUsuarios VeD_CreacionNavigation { get; set; }
        public virtual tbUsuarios VeD_ModificaNavigation { get; set; }
        public virtual tbVentasEnc VeE { get; set; }
        public virtual tbVehiculos Veh_PlacaNavigation { get; set; }
    }
}